.TH "PACKUP" "1" "April 2009" "" ""
.SH "NAME"
packup \- a simple backup & restore script for pacman

.SH "SYNOPSIS"
packup
.SH "DESCRIPTION"
Packup is a simple script that allows a user to take a snapshot of all the packages that are currently installed, as well as subsequently restoring those snapshots at a later date (or on a different computer).
.SH "OPTIONS"
.TP 
\fB\-h\fR, \fB\-\-help\fR
Display the help message
.TP 
\fB\-v\fR, \fB\-\-version\fR
Output version information and exit
.TP 
<fb>\-w\fR, \fB\-\-welcome\fR
Displays the welcome dialog
.SH "AUTHORS"
Ghost1227
